#ifndef AUDIO_ME_H
#define AUDIO_ME_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// 12.20 fixed-point resampler state
typedef struct {
  uint32_t location;      // current source position in 12.20 fixed-point
  uint32_t adder;         // step per output sample in 12.20 fixed-point
  uint32_t source_count;  // number of source samples to resample from
} AudioResamplerState;

// ME-owned audio buffers. CPU and ME each own a side of the double-buffer.
typedef struct {
  int16_t *buffer[2];
  uint32_t buffer_size;  // target output count per buffer (stereo sample pairs)

  AudioResamplerState resampler;

  volatile uint32_t me_write_idx; // which buffer ME is writing to
  volatile uint32_t cpu_read_idx; // which buffer CPU should read from
  volatile int me_ready;         // 1 when a ME-generated frame is ready
  volatile int me_fault;         // 1 if the ME path failed

  uint32_t target_samples; // output samples per frame
  uint32_t source_samples; // input samples per frame
} AudioMeBuffer;

// Initialize the ME-owned audio buffer pool.
int AudioMeBufferInit(AudioMeBuffer *buf, uint32_t target_samples, uint32_t source_samples);

// Tear down the ME-owned buffer pool.
void AudioMeBufferShutdown(AudioMeBuffer *buf);

// Queue raw DSP audio for ME resampling.
// Returns 0 on success, -1 on invalid input.
int AudioMeEnqueueDspSamples(AudioMeBuffer *buf, const int16_t *dsp_samples, uint32_t dsp_count);

// Retrieves the next frame generated by ME.
// Returns NULL if no ME frame is ready yet.
int16_t *AudioMeGetNextFrame(AudioMeBuffer *buf);

// ME-side kernel: resample input source into the current ME write buffer.
void AudioMeResampleKernel(AudioMeBuffer *buf, const int16_t *src);

#ifdef __cplusplus
}
#endif

#endif // AUDIO_ME_H
